const blankFieldErrorMessage = 'Please provide all the details';
const noUserFoundErrorMessage = 'User with this email does not exists';
const notificationSenderUrl = 'https://fcm.googleapis.com/fcm/send';
const inviteMailMessage = 'Hurray, mail is successfully sent to ';
const letterSentMessage = 'Your letter is successfully sent to ';
const replySentMessage = 'Your reply is successfully sent to ';
const letterReadMessage = 'Your letter is read by '
const replyReadMessage = 'Your reply is read by '
const notRegisterErrorMessage = 'Please register to write back then check again later'
const mailSubjectLetter = 'Pending Letters';
const mailLetterText1 = 'Hey, you have pending letters from ';
const mailLetterText2 = '. Please register to write back to check all of the pending letters.';
const mailSubjectReply = 'Pending Replies';
const mailReplyText1 = 'Hey, you have pending replies from ';
const mailReplyText2 = '. Please register to write back to check all of the pending replies.';
const loginMessage = 'You are logged in';
const signupAndLoginMessage = 'New account created and you are logged in'
const feelingUpdateMessage = 'Feelings updated successfully';
const fcmUpdateMessage = 'Fcm token updated successfully';
const imageUpdateMessage = 'Image updated successfully';
const sendFriendRequest = 1;
const acceptOrDeclineFriendRequest = 2;
const requestPendingFromOtherSide = 3;
const acceptedFriendRequest = 4;
const scribbleSaved = 'Scribble saved successfully';
const scribbleUpdated = 'Scribble updated successfully';
const friendRequestSent = 'Friend request sent successfully';
const friendRequestAlreadySent = 'Friend request already sent';
const friendRequestWithdraw = 'You have withdrawn friend request from ';
const invalidFriendRequestWithdraw = 'Invalid call for cancelling the request';
const invalidFriendRequestAccept = 'Invalid call for accepting the request';
const invalidFriendRequestDecline = 'Invalid call for declining the request';
const invalidLetter = "You don't have any letter with this letter id";
const invalidReply = "You don't have any reply with this reply id";
const accessDeniedToUpdateScribble = 'You do not have access to update this scribble';
const friendRequestNotification = 'New friend request notification sent'
const friendRequestNotificationTitle = 'New friend request';
const friendRequestNotificationText = 'You have received friend request from ';
const friendRequestAcceptedNotification = 'Friend request accepted notification sent';
const friendRequestAcceptedNotificationTitle = 'Yeah, friend request accepted';
const friendRequestAcceptedNotificationText1 = 'You and ';
const friendRequestAcceptedNotificationText2 = ' are friends now';
const letterSentNotification = 'New letter notification sent';
const letterSentNotificationTitle = 'New letter received';
const letterSentNotificationText = 'You received a letter from ';
const replySentNotification = 'New reply notification sent';
const replySentNotificationTitle = 'New reply received';
const replySentNotificationText = 'You received a reply from ';
const letterReadNotification = 'Letter read notification sent';
const letterReadNotificationTitle = 'Letter read status';
const letterReadNotificationText = 'Hurray, your letter is read by ';
const replyReadNotification = 'Reply read notification sent';
const replyReadNotificationTitle = 'Hurray, your reply is read by ';
const replyReadNotificationText = 'Reply read status';
const feelingUpdateNotification = 'Update feeling notification sent';
const feelingUpdateNotificationText = "'s feeling get updated";
const feelingUpdateNotificationTitle = "Friend's feeling updated";
const removeFriend1 = 'You have removed ';
const removeFriend2 = ' from your friend list';
const limitOfData = 20;

module.exports = {blankFieldErrorMessage, noUserFoundErrorMessage, notificationSenderUrl, inviteMailMessage, letterSentMessage, letterReadMessage, notRegisterErrorMessage, mailSubjectLetter, mailLetterText1, mailLetterText2, mailSubjectReply, mailReplyText1, mailReplyText2, loginMessage, signupAndLoginMessage, feelingUpdateMessage, fcmUpdateMessage, imageUpdateMessage, sendFriendRequest, acceptOrDeclineFriendRequest, scribbleSaved, scribbleUpdated, friendRequestAlreadySent, friendRequestSent, friendRequestWithdraw, invalidFriendRequestWithdraw, requestPendingFromOtherSide, invalidFriendRequestAccept, invalidFriendRequestDecline, acceptedFriendRequest, invalidLetter, accessDeniedToUpdateScribble, friendRequestNotificationText, friendRequestNotificationTitle, friendRequestNotification, friendRequestAcceptedNotification, friendRequestAcceptedNotificationTitle, friendRequestAcceptedNotificationText1, friendRequestAcceptedNotificationText2, letterSentNotification, letterSentNotificationText, letterSentNotificationTitle, replySentNotification, replySentNotificationTitle, replySentNotificationText, replySentMessage, letterReadNotification, letterReadNotificationTitle, letterReadNotificationText, replyReadNotification, replyReadNotificationTitle, replyReadNotificationText, replyReadMessage, invalidReply, feelingUpdateNotification, feelingUpdateNotificationTitle, feelingUpdateNotificationText, removeFriend1, removeFriend2, limitOfData};